from itertools import product
from time import sleep


rules = dict()
messages = []
#with open('input/input19.txt') as f:
with open('input/input19.txt') as f:
    for line in f:
        line = line.strip()
        if ':' in line:
            num, pattern = line.split(': ')
            pattern_list = []
            if '|' in pattern:
                pattern_list = pattern.split(' | ')
                pattern_list = [tuple([int(x) for x in y.split()]) for y in pattern_list]
            elif '"' in pattern:
                pattern_list = [pattern[1:-1]]  # should be a single letter
            else:
                pattern_list = [tuple([int(x) for x in pattern.split()])]

            rules[int(num)] = pattern_list
        elif len(line) > 0:
            messages.append(line)


"""
class tree:
    def __init__(self):
        self.branches = []
        self.val = None

    def add(self, t):
        self.branches.append(t)

    def add_value(self, v):
        self.val = v

    def value(self):
        return self.val


def combine_elems(left, right):
    # elements are lists of tuples
    # elem = [(a, b, c, ...), (d, a, b...), ...]
    c = []
    for e_left in left:
        for e_right in right:
            c.append(tuple(list(e_left)+list(e_right)))
    # print(left, right, c)
    return c


rule_0 = tree()
rule_0.add_value([0])
queue = [rule_0]
while len(queue) > 0:
    print(len(queue))
    if len(queue) > 100000:
        sleep(1)
    node = queue.pop(0)
    pattern = node.value()

    if any([str(x).isdigit() for x in pattern]):
        branched_pattern = []
        for elem in pattern:
            if elem not in ['a', 'b']:
                new_elem = rules[elem]

                # guarantee each branch will be split
                while len(new_elem) == 1 and any([str(x).isdigit() for x in new_elem[0]]):
                    new_new_elem = [()]
                    for n in new_elem[0]:
                        if n in ['a', 'b']:
                            new_new_elem = combine_elems(new_new_elem, [n])
                        else:

                            new_new_elem = combine_elems(new_new_elem, rules[n])

                    new_elem = new_new_elem
                    

                branched_pattern.append(new_elem)
            else:
                branched_pattern.append([elem])


        for p in product(*branched_pattern):
            # p is a list of tuples but these should be combined left to  right
            # to make a pattern
            p = sum([list(x) for x in p], [])  # single list of numbers and letters
            t = tree()
            t.add_value(p)
            node.add(t)
            queue.append(t)


quit()
def get_all(t):
    strings = []
    for b in t.branches:
        if len(b.branches) > 0:
            strings += get_all(b)
        else:
            strings.append(''.join(b.value()))
    return strings


print(get_all(rule_0))
"""


mem = dict()
def get_all(num):
    # Return all strings generated by a rule.
    if num not in mem:
        pattern = rules[num]
        all_strings = []
        for branch in pattern:
            if branch in ['a', 'b']:
                all_strings.append(branch)
            else:
                sub_strings = []
                for n in branch:
                    sub_strings.append(get_all(n))

                branch_strings = product(*sub_strings)
                branch_strings = [''.join(x) for x in branch_strings]
                all_strings += branch_strings

        mem[num] = all_strings

    return mem[num]


allowed = set(get_all(0))


def check_extended(m):
    # can match x 42 followed by y 31.
    # x > y strictly.
    # Since every value for 42 and 31 is of length 8 I can just cut m into
    # length 8 segments.
    # It is also important to note they have no overlap.
    s_42 = get_all(42)
    s_31 = get_all(31)

    ind = 0
    count_42 = 0
    count_31 = 0
    have_switched = False
    while ind < len(m):
        s = m[ind:ind+8]
        if s in s_42:
            count_42 += 1
            if have_switched:
                return False
        elif s in s_31:
            have_switched = True
            count_31 += 1
        else:
            return False

        ind += 8

    if 1 <= count_31 < count_42:
        return True
    return False


count_1 = 0
count_2 = 0
for m in messages:
    if m in allowed:
        count_1 += 1
    if check_extended(m):
        count_2 += 1
print(count_1)
print(count_2)
